export const OffFlagBB = [
  "Kearsarge",
  "New Jersey",
  "Friedrich der Große",
  "Flandre",
  "Daisen",
  "Odin",
  "Vittorio Veneto",
  "Howe",
  "Gneisenau",
  "Rodney",
  "Repulse",
  "Warspite",
  "Champagne",
  "Georgia",
  "Tosa",
  "Renown",
  "Scharnhorst",
  "Gascogne μ",
  "Jean Bart",
  "Prince of Wales",
  "Hyuuga",
  "Queen Elizabeth",
  "Vanguard",
  "Alsace",
  "Musashi",
  "Bismarck Zwei",
  "Sovetsky Soyuz",
  "Ulrich von Hutten",
  "Owari",
  "Seydlitz",
  "Constellation",
  "Indiana",
  "Strasbourg",
  "Clemenceau",
  "Roma",
  "Alvitr",
  "São Martinho",
  "Brünhilde",
  "Royal Oak",
  "Tamaki",
  "Fubuki (Senran Kagura)",
  "Iori Minase",
]
