name: Automated ECGC Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update-ecgc:
    runs-on: ubuntu-latest
    name: Run ECGC Devtools and Commit Changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.19"

      - name: Install dependencies
        run: |
          bun update
          bun install

      - name: Restore credentials
        run: |
          echo "$GOOGLE_CREDENTIALS_BASE64" | base64 -d > dev/python/credentials.json
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}

      - name: Run devtools
        run: bun run devtools

      - name: Commit and push changes if any
        run: |
          git config --global user.name "ECGC Bot"
          git config --global user.email "ecgc-bot@users.noreply.github.com"

          if [[ -n $(git status --porcelain) ]]; then
              DATE=$(date +"%m/%d/%Y")
              git add .
              git commit -m "Chore(ecgc): Automated Site Update: $DATE"
              git push -f
          else
              echo "No changes to commit."
          fi

      - name: Clean up credentials
        if: always()
        run: |
          rm -f dev/python/credentials.json
