name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
    paths:
      - "packages/frontend/**"
      - "packages/AzurLaneData/**"
      # - "wrangler.jsonc"
      # - "package.json"
      # - ".github/workflows/cf-deploy.yml"
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: CF-Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.20"

      - name: Install dependencies
        run: bun install

      - name: Deploy to Cloudflare Workers
        run: bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
