name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
    paths-ignore:
      - "dev/**"
      - "bun.lock"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Check for only devDependency changes
        id: dev-deps
        run: |
          git fetch origin main --depth=1
          git diff origin/main HEAD -- package.json > changes.diff
          if [ -s changes.diff ]; then
            if jq -e '(.dependencies // {}) == (input | .dependencies // {})' package.json origin/main:package.json >/dev/null; then
              echo "Only devDependencies changed. Skipping deploy."
              echo "skip=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Install dependencies
        run: bun install

      - name: Deploy to Cloudflare Workers
        run: bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
