name: ECGC Ephemeral

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - "packages/frontend/**"
      - "packages/AzurLaneData/**"

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.0"

      - name: Install dependencies
        run: bun install

      - name: Compress Build
        run: bun run compress-build

      - name: Upload Worker Version for Preview
        id: upload
        run: |
          # Get branch name and sanitize for alias
          BRANCH_NAME="${{ github.head_ref }}"
          SANITIZED_ALIAS=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-*$//g' | sed 's/^-*//g' | cut -c1-30)

          echo "Branch: $BRANCH_NAME"
          echo "Sanitized alias: $SANITIZED_ALIAS"

          # Upload new version with branch-based alias for consistent preview URL
          VERSION_OUTPUT=$(bunx wrangler versions upload --preview-alias "$SANITIZED_ALIAS" 2>&1)
          echo "$VERSION_OUTPUT"

          # Extract preview URL from wrangler output (format: <alias>-ecgc-dev.samheart564.workers.dev)
          PREVIEW_URL=$(echo "$VERSION_OUTPUT" | grep -o "https://$SANITIZED_ALIAS-ecgc-dev\.samheart564\.workers\.dev" | head -1)

          if [ -z "$PREVIEW_URL" ]; then
            echo "Error: Could not find preview URL in deployment output"
            exit 1
          fi

          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "Preview URL: $PREVIEW_URL"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Comment PR with Preview URL
        uses: thollander/actions-comment-pull-request@v3
        if: success()
        with:
          message: |
            ## 🚀 Preview Deployment Ready

            **Branch:** `${{ github.head_ref }}`
            **PR:** #${{ github.event.number }}
            **Commit:** `${{ github.event.pull_request.head.sha }}`

            **🔗 Preview URL:** ${{ steps.upload.outputs.preview_url }}

            ---
            *This preview deployment will be automatically updated when you push new commits to this branch.*
          comment-tag: preview-url
          mode: upsert
